### ISSUE TITLE
Feature Request: Change Calendar Week Style

### ISSUE THREAD

**Issue by JoeArcher007** [in0rdr/diary#13]
Just another suggestion, I'm not too sure if this is dependent on the users locale, but it appears that diary has the week start on Monday, as in

M-T-W-T-F-S-S

Would it be possible to get a switch to change it to 

S-M-T-W-T-F-S

Thanks!

**Comment by in0rdr** [comment]
Thank you for your suggestion! I like this idea.
This would make a good case to create a configuration file for the diary (or a switch as you said).

I don't know much about locales in terminal but if we could take that into consideration would be great!

**Comment by in0rdr** [comment]
Hi @JoeArcher007, finally, I could hack on the config file. The `first_weekday` is a supported configuration key, among others (master/latest, future v0.5): https://github.com/in0rdr/diary/pull/61

Feel free to review or improve it further. I was thinking to add support through the option arguments as well, so that you could simply start the program with `diary --first_weekday=0`.

**Comment by JoeArcher007** [comment]
This is amazing news @in0rdr

Not going to lie I haven't used the diary in a long while, but should make that a resolution to get back into it. I'll load this one up on my machine (as soon as I am done repairing it) and give it a go!

**Comment by in0rdr** [comment]
The first weekday is now fully configurable through command line options or the (optional) configuration file, see [release 0.5](https://github.com/in0rdr/diary/releases/tag/v0.5). The [package repository](https://software.opensuse.org/download.html?project=home%3Ain0rdr&package=diary) will include this new release shortly.
