### ISSUE TITLE
Directory Structure

### ISSUE THREAD

**Issue by in0rdr** [in0rdr/diary#19]
`~/local/share/diary/diary/2016/Jan`

**Comment by livibetter** [comment]
In my personal opinion, I think that's over-complicating and I question if anyone would actually go deep into directories, besides, it's really easy to list for files, e.g. `ls 2016-*`, `ls 2016-01-*`.

But, that definitely is doable and I think if you are going to do it, go little overboard, make it an option, so that user can choose their own structure using date format like `%Y/%b`, then recursively check/create required directories.
