### ISSUE TITLE
Stashing instead of deleting.

### ISSUE THREAD

**Issue by ghost** [in0rdr/diary#21]
I believe that deleting entries is too dangerous feature to have in the main interface. Instead the entries should just be "hidden" so if an user accidentally deletes a diary entry it could be recovered. This would be easy enough to achieve by moving them to some kind of stash/backup directory instead of deleting them.

In the future it would be possible to add a mode for browsing the stash and recovering entries but since they can be just files in a directory there wouldn't be any hurry for implementing that.

Applying some kind of weak cipher such as rot13 to the stashed entries would be desirable for those who want to `grep -r` the diary directory, or some parent directory of it and don't want to match the entries in the stash.

In reddit PM @in0rdr suggested that a version control such as git could be used instead but I don't believe this would be an appropriate solution unless some kind of hook system was implemented and this could end up being much more complicated than just moving the the deleted entries to a stash.

**Comment by shaggytwodope** [comment]
I'm all for a "stash". However how would "merging" deleted entries work? If it's just for reference then has no issue I can see.

**Comment by Tsutsukakushi** [comment]
>  However how would "merging" deleted entries work?

Stash current one, recover the one you want was the workflow I was thinking of.

I guess some option to open current entry and selected stashed entry with vimdiff or something similiar could work as well.

**Comment by shaggytwodope** [comment]
That makes sense how you want to go about it. It'd be nice to show a possible comparison. Even with no feature to merge.

**Comment by Tsutsukakushi** [comment]
> It'd be nice to show a possible comparison. Even with no feature to merge.

This would be possible by just changing the diff program. People who use `vimdiff` could edit, people who set it to `diff -y -d` or something similiar could see the difference. Obviously in case of a non-interactive differ it would also have to be piped into a pager so it won't exit immediately.

**Comment by livibetter** [comment]
Personally, I think this makes thing too complicated. But I think I have a compromised option, rename diary entry filename `YYYY-MM-DD` to `.YYYY-MM-DD`.

It's not deletion, but hidden action <sup>a</sup>. And what user want to create a new one (or hide again) on a date with hidden entry, the user gets a warning.

<sup>a</sup>: Of course, the hidden is just for file listing command. For grep, `*` won't expand to hidden filenames.

Git, as @in0rdr suggested as mentioned in OP's post, is really a better option, the functionality is already there for what OP wants, that literally is `stash`, but really unnecessary if you commit anything changed.

About hook, you can just wrap `diary` with a script and every time it exits, check with `git status`, if changes (including new files not in repository), auto-commit using timestamp as commit message.

The only drawback with Git is the user has to have Git, which isn't a big issue, good chance Git is already installed, the real problem is the user needs to know how to use Git when wanting to recover stuff.

Frankly, I don't think we need anything done for this, Git can do, but if have to, whether hidden file approach or any other method, this has to be optional option, not by default. Please KISS.
