### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by ghost** [in0rdr/diary#23]
Some kind of template for a new entry would be a nice addition. What this means is that when creating a new entry instead of openingn an empty file an empty template would be opened instead. This is a desirable feature for people who have sections in their diary that are present in (almost) all entries.

**Comment by mbjd** [comment]
You could do this pretty easily by adjusting the editor string to a command that reads in a template file when starting the editor. For example, for vim you could use:

    vim -c ':r ~/.diary_template.txt' <diary_file>

You'd just have to watch out that you only do this when creating a new file, and not every time you open the editor.

A barebones, hacky implementation could go like this: In the `edit_cmd` function, check if an entry already exists with `date_has_entry`. If so, call the existing code to simply edit the file. Otherwise, replace the `editor` string with the command above: `"vim -c ':r ~/.diary_template.txt'"`

**Comment by livibetter** [comment]
@mbjd that is a great idea, and I think we don't even need to hack diary's code, just `alias` and use of `EDITOR` environment:

```bash
alias diary="EDITOR='vim -c \":r ~/.diary_template.txt\"' diary"
```

The drawback is it's editor dependent, but come to think about this issue, it's already editor dependent, since diary need to tell the *specific* editor to load the template file and save as the diary file, unless diary always creates the diary file using template text regardless if the user actually write the diary.

So, I think this issue should not be implemented (more like impossible to implement), because you just can't cover all editors even if all editors support like Vim does.

(Of course, we can check if the diary file is unchanged, but that's more code in diary when a simple alias can already do what we need)

**Comment by Tsutsukakushi** [comment]
This $EDITOR implementation would limit the feature to only specific editors. For example `nano` users could not have templates for their entries.

Also it should only happen when a entry is created. Doing it in the $EDITOR like in your example would mean that every time you edit an entry the template would be appended.

**Comment by livibetter** [comment]
@Tsutsukakushi probably need a script instead to check if the diary file already exists, or just change the vim command to check if the file has any content. 

Since you opened this issue, you must have put some thoughts in this, have you come up a way that would work best for most editors?

**Comment by livibetter** [comment]
Frankly, I can only think of one way that would work for all editors, if must be done inside diary.

If the diary entry file does not exist, then:

1. copy the template file to diary directory as the diary entry file.
2. save diary entry file's timestamp.
3. run the `$EDITOR`.
4. after editor exits, check the timestamp. If not changed, remove the diary entry file.

**Comment by Tsutsukakushi** [comment]
@livibetter which is basically what I was suggesting.

**Comment by livibetter** [comment]
@Tsutsukakushi I guess I have gone a big circle. I saw you have a couple of C projects, why don't you make a PR? I think we can hard-code the template location at `$XDG_CONFIG_HOME/diary/template` at this moment before #35 is done, or whatever a better location for default template file that you can think of.

**Comment by in0rdr** [comment]
I also think copying is a solid and simple solution for this feature request.

@livibetter, I do not understand why you want to save the timestamp. Isn't it enough to check if the file exists (or even if it is empty or not) and if the entry does not exist (or is empty in the advanced version), copy the template before the editor cmd?

**Comment by in0rdr** [comment]
So basically I would go with what @mbjd suggested for a first proof of concept, but I would seperate the copy command from the editor command.

Thanks.

**Comment by livibetter** [comment]
@in0rdr you misunderstood, read the steps again in my previous comment, including the "if" above the steps. We will want to check if user does save the diary, and that's where the timestamp comes in. Unless, you want user to manually delete unedited copied template after exiting editor.

**Comment by livibetter** [comment]
@in0rdr I thought you meant @Tsutsukakushi's suggest not @mbjd at first read of your reply, so just to be sure, you want to take the editor-dependent approach, in this case Vim only, right?

> A barebones, hacky implementation could go like this: In the `edit_cmd` function, check if an entry already exists with `date_has_entry`. If so, call the existing code to simply edit the file. Otherwise, replace the editor string with the command above: **`"vim -c ':r ~/.diary_template.txt'"`**

**Comment by Tsutsukakushi** [comment]
@livibetter because I'm a bit too busy for that, unfortunately.
