### ISSUE TITLE
[Feature Request] Color/Colour options?

### ISSUE THREAD

**Issue by aphirst** [in0rdr/diary#43]
I'm aware that `diary` is intended to be simple, but would it be out-of-scope to have some sort of (maybe optional?) syntax for colour-coding lines or segments of text? I'm aware that my `EDITOR` might well have this feature, but this doesn't apply to the preview here.

Even something simple like prefixing a line with a symbol like !, # @ etc. with a colour for each might be enough.

But at the same time, definitely non-essential. I'm liking this tool so far *because* of its simplicity. :-)

**Comment by in0rdr** [comment]
Thank you for this suggestion, good idea. Yes, it is intended to be that simplistic, without any formatting and coloring so anybody can use it.

If we implement such a feature, we should do it "plugin/addon-like", because formatting is very individual. So maybe at compile time you can specify, which coloring or formatting options you want in your diary preview. Or even a settings file would be great, where you could have a simple default setting but get as sophisticated as you wish.
