### ISSUE TITLE
[Feature Request] markdown support

### ISSUE THREAD

**Issue by prankousky** [in0rdr/diary#44]
Similar to the previous request: would it be possible to add markdown support?

I just stumbled upon diary and it is great! It does exactly what I need it to. However, when writing longer entries and trying to emphasize something, it'd be so great do just do `**important**` and have it be **bold**.

My EDITOR is vim, and vim has markdown support. However, when I select an entry via the calendar, it will display it as is and have the asterisks just be asterisks, not render the word in between them bold.

Unfortunately, I do not have the skills to implement something like this myself (in the previous request, plugins were considered), so I have to ask here for it ^^ 

Keep up the good work 👍

**Comment by in0rdr** [comment]
Hi @prankousky thank you for your request. Unfortunately, I don't think I can find time to implement this any time soon, so I will close it for the time being. Hope this is fine :) Thanks.

**Comment by in0rdr** [comment]
Hi @prankousky. While implementing a request to support a custom text format utility (#68), I recognized that this will also allow us to use a Markdown format command to pre-format the entry before preview.

Coloring is difficult though, if not impossible to implement without writing tons of code (we simply write the entire output returned from the text format command to the terminal and don't invoke the Ncurses attribute changes for changing colors, i.e., Ncurses does not support the ANSI color codes of the terminal):
- https://tldp.org/HOWTO/NCURSES-Programming-HOWTO/color.html
- https://stackoverflow.com/a/33210354
- https://gitlab.com/muttmua/mutt/-/blob/master/pager.c#L1036

So, adding this in our code is not enough:
```
     initscr();
+    start_color();
+    use_default_colors();
```

But what you can do now with the latest addition on the master branch - plug any Markdown format command into `--fmt-cmd` or the [config file](https://github.com/in0rdr/diary/#Configuration-File):
```
# ~/.config/diary/diary.cfg
# Text formatting command/utility
fmt_cmd = mdcat -c
```
https://github.com/lunaryorn/mdcat

The `-c` is for "no color". Otherwise, you will simply see the ANSI escape characters for the color in the preview, which is not nice.

I like the style of the checkboxes :)

Not sure though if I will continue to use this on a daily basis, since the character to denote the headings seems a bit weird to me..

**Comment by in0rdr** [comment]
Hi @prankousky,

Give the latest `diary-nightly` package a try.

I added some code to preview the journal entries on [pseudo terminal (pty)](https://www.gnu.org/software/libc/manual/html_node/Pseudo_002dTerminals.html) (the result of `--fmt-cmd` is printed on a pty).

This is enabled by default, you just have to use your `fmt_cmd` (`-F`) of choice to format the entries, e.g.:
```bash
diary --fmt-cmd="mdcat"
```

You can persist these settings in the config file.

This should allow us to do all the fancy Markdown things we are used to, incl. boldface, italics, headings, code, etc

![Screenshot from 2021-12-11 19-50-35](https://user-images.githubusercontent.com/9302430/145688334-4f16c1ca-88de-4a1f-8c2f-0c0f9f877298.png)
