### ISSUE TITLE
Feature Request: Date Search

### ISSUE THREAD

**Issue by JoeArcher007** [in0rdr/diary#7]
I know the program isn't that old, but it would be excellent to have a search function for date. 

For instance, possibly hitting "s" would enable date search, and you could type in the format the same as how the text files are made. Or possibly any date style with conversion. 

Love the little program though! Keep up the good work.

**Comment by in0rdr** [comment]
Thank you for your request! Very good suggestion.

I just pushed a first try on unstable branch [feature/search](https://github.com/in0rdr/diary/commits/feature/search).
Unfortunately the cursor gets not updated. Needs still more work.

**Comment by JoeArcher007** [comment]
That's awesome! I'll have to get a test version out and see how it operates. Thanks for looking into it.

**Comment by in0rdr** [comment]
Hi, I figured it out and pushed directly to master, see [here](https://github.com/in0rdr/diary/commit/5f6eace2ff80b2b3006e0dcad61bde60c015a287)

I needed to subtract 1900 from the year and 1 from the month, because the C tm struct counts the years since 1900 and the months are in range [0,11]

Thanks!

**Comment by JoeArcher007** [comment]
Awesome. That's excellent. I reviewed it, looks great! Thanks again.
