### ISSUE TITLE
claws mail ics import

### ISSUE THREAD

**Issue by kristoferus75** [in0rdr/diary#76]
Hi !

I use claws mail and i get my invitations with a mail !
the plugin i use is vCalendar -> i export the calendar automatically to this file claws-mail.ics

Is it possible to import claws-mail.ics in diary ?

thanks

regrads

**Comment by in0rdr** [comment]
Yes, it would be possible but it's not implemented yet. The CalDAV sync code already contains some utility functions to "parse" these kind of VEVENTS.

There is also a task on my list to handle multiple events returned from a CalDAV request. I suppose that is similar to parsing an ics file from disk.

https://github.com/in0rdr/diary/issues/75

So it would be possible, but not implemented yet, even though some code blocks might already exist.

Does this answer your question?

I will certainly consider this kind of functionality in the future (also export to ics file), thanks for bringing it up here.

On 19 Sep 2021, at 09:17, kristoferus75 ***@***.***> wrote:

﻿

Hi !

I use claws mail and i get my invitations with a mail !
the plugin i use is vCalendar -> i export the calendar automatically to this file claws-mail.ics

Is it possible to import claws-mail.ics in diary ?

thanks

regrads

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kristoferus75** [comment]
Yes Thanks !
